# Generated by Django 2.1.1 on 2018-10-20 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('motto', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='static/club_image')),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Club_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/event_image')),
                ('fees', models.IntegerField()),
                ('date', models.DateField()),
                ('club_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_activities.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='static/gallery')),
                ('ename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_activities.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_user', models.CharField(choices=[('A', 'Admin'), ('CA', 'College Admin'), ('O', 'Others')], default='O', max_length=10)),
                ('club', models.ManyToManyField(to='club_activities.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=30)),
                ('sem', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registered_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_activities.Profile')),
                ('ename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_activities.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_activities.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club_activities.Profile'),
        ),
        migrations.AddField(
            model_name='club_request',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_activities.Profile'),
        ),
    ]
