# Generated by Django 2.1.1 on 2018-10-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='misson',
            field=models.TextField(blank='True'),
        ),
        migrations.AddField(
            model_name='club',
            name='vission',
            field=models.TextField(blank='True'),
        ),
    ]
