# Generated by Django 2.1.1 on 2018-10-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_activities', '0002_auto_20181021_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club_activities.Club'),
        ),
    ]
