# Generated by Django 2.1.1 on 2018-10-21 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_activities', '0003_request_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='club',
        ),
        migrations.AddField(
            model_name='member',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club_activities.Event'),
        ),
    ]
