# Generated by Django 2.1.1 on 2018-10-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_activities', '0005_auto_20181021_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='shortdesc',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank='True', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(blank='True', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.CharField(blank='True', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.CharField(blank='True', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank='True', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.IntegerField(blank='True'),
        ),
    ]
