# Generated by Django 2.1.1 on 2018-10-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_activities', '0011_event_smalldesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='misson',
            new_name='mission',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='vission',
            new_name='vision',
        ),
    ]
