# Generated by Django 2.1.1 on 2018-10-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_activities', '0012_auto_20181023_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
