# Generated by Django 2.1.1 on 2018-10-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_activities', '0013_request_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(max_length=30, null='True'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(max_length=100, null='True'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.CharField(max_length=30, null='True'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.CharField(max_length=30, null='True'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=100, null='True'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.IntegerField(null='True'),
        ),
    ]
