# Generated by Django 2.1.1 on 2018-10-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_activities', '0014_auto_20181025_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_request',
            name='mission',
            field=models.TextField(blank='True'),
        ),
        migrations.AddField(
            model_name='club_request',
            name='vision',
            field=models.TextField(blank='True'),
        ),
    ]
