# Generated by Django 2.1.1 on 2018-10-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_activities', '0016_auto_20181025_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(null=True, upload_to='static/club_image'),
        ),
        migrations.AlterField(
            model_name='club',
            name='mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='mission',
            field=models.TextField(null='True'),
        ),
        migrations.AlterField(
            model_name='club',
            name='motto',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='vision',
            field=models.TextField(null='True'),
        ),
    ]
